FROM python:3.8-slim


COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt


COPY . /app
WORKDIR /app


RUN pip install uvicorn gunicorn


CMD ["uvicorn", "web_API_AMVERA_1:app", "--host", "0.0.0.0", "--port", "8025"]